//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CommTest.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_POPUP_WORKSPACE             119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_CommTestTYPE                130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND_HC           168
#define IDB_WORKSPACE_NEW               170
#define IDR_WORKSPACE_NEW               171
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_POPUP_OUTPUT                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_WORKSPACE_NEW_TEST           185
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDB_WORKSPACE                   310
#define IDB_BITMAP_LIST                 311
#define IDD_DLG_CLIENT_SEND             312
#define IDD_DLG_CLIENT_RECV             313
#define IDD_DLG_NEW_CLIENT              314
#define IDD_DLG_CLIENT_OPTIONS          317
#define IDD_DLG_NEW_PING                318
#define IDD_DLG_PING_OPTIONS            319
#define IDB_BMP_FLAG                    320
#define IDR_POPUP_PACKET                321
#define IDR_PACKET_DECODE               322
#define IDD_DLG_PACKET_DETAIL           323
#define IDD_DLG_NEW_SVR                 324
#define IDD_DLG_SVR_OPTIONS             325
#define IDD_DLG_SVR_RECV                326
#define IDD_DLG_SVR_SEND                327
#define IDR_POPUP_TOOLBAR               350
#define IDR_POPUP_MDITABS               351
#define IDR_POPUP_DROP_MDITABS          352
#define IDR_PING_TEST                   401
#define IDR_CLIENT_COMM                 402
#define IDR_POPUP_SORT1                 403
#define IDR_POPUP_WORKSPACE_TOOLBAR     404
#define ID_STRING_ETH                   500
#define ID_STRING_CLIENT_MODE           501
#define ID_STRING_SVR_MODE              502
#define ID_STRING_PING_MODE             503
#define ID_STRING_COM                   504
#define ID_SEVER_LIST                   506
#define IDC_IPADDRESS_DEST              1000
#define IDC_CB_PROTO_TYPE               1001
#define IDC_RADIO_LOCAL_PORT1           1002
#define IDC_RADIO_LOCAL_PORT2           1003
#define IDC_EDIT_DEST_PORT              1004
#define IDC_EDIT_LOCAL_PORT             1005
#define IDC_EDIT_DEST_PORT_OPT          1006
#define IDC_CHECK_LOCAL_PORT            1007
#define IDC_CHECK_HEX                   1009
#define IDC_BUTTON_RESET                1010
#define IDC_BUTTON_START                1011
#define IDC_STATIC_SND_CNT              1012
#define IDC_STATIC_RCV_CNT              1013
#define IDS_MAIN_TOOLBAR                1014
#define IDC_EDIT_LOCAL_PORT_OPT         1015
#define IDC_CB_PROTO_TYPE_OPT           1016
#define IDC_EDIT_SEND_TXT               1017
#define IDC_BUTTON_SEND                 1018
#define IDC_BUTTON_CLEAR_SEND           1019
#define IDC_BUTTON_STOP                 1020
#define IDC_BUTTON_ADV                  1021
#define IDC_IPADDRESS_DEST_OPT          1022
#define IDC_EDIT_INT_TIME               1023
#define IDC_BUTTON_CLEAR_RECV           1024
#define IDC_IPADDRESS_PING_DEST         1025
#define IDC_EDIT_PING_DATA_SIZE         1026
#define IDC_EDIT_PING_THREAD_CNT        1027
#define IDC_EDIT_PING_INT_TIME          1028
#define IDC_CHECK_TIMEOUT_DELAY         1029
#define IDC_IPADDRESS_PING_DEST_OPT     1030
#define IDC_EDIT_PING_THREAD_CNT_OPT    1031
#define IDC_BUTTON_PING_START           1032
#define IDC_STATIC_PACKET_TIME          1033
#define IDC_STATIC_PACKET_ID            1034
#define IDC_STATIC_TREE_LOC             1035
#define IDC_BUTTON_DISP                 1036
#define IDC_CHECK_AUTO_SEND             1037
#define IDC_STATIC_PING_LOST_CNT        1038
#define IDC_EDIT_SVR_PORTNUM            1039
#define IDC_COMBO_HOST_IP               1040
#define IDC_BUTTON_SVR_START            1041
#define IDC_STATIC_PING_RTN_CNT         1042
#define IDC_COMBO_HOST_IP_OPT           1043
#define IDC_STATIC_PING_SND_CNT         1044
#define IDC_EDIT_SVR_INT_TIME           1046
#define IDC_CHECK_SVR_HEX               1047


#define IDC_EDIT_SVR_SEND_TXT           1051
#define IDC_EDIT_SVR_PORTNUM_OPT        1052
#define IDC_CHECK_SVR_AUTO_SEND         1053
#define IDC_BUTTON_SVR_SEND             1054
#define IDC_BUTTON_SVR_STOP             1055
#define IDC_BUTTON_SVR_CLEAR_SEND       1056
#define IDC_BUTTON_SVR_ADV              1057
#define IDC_BUTTON_SVR_DISP             1058
#define IDC_BUTTON_SVR_CLEAR_RECV       1059
#define ID_WORKSPACE_NEW                1200
#define ID_WORKSPACE_DELETE             1201
#define ID_VIEW_USER_TOOLBAR1           2793
#define ID_VIEW_USER_TOOLBAR2           2794
#define ID_VIEW_USER_TOOLBAR3           2795
#define ID_VIEW_USER_TOOLBAR4           2796
#define ID_VIEW_USER_TOOLBAR5           2797
#define ID_VIEW_USER_TOOLBAR6           2798
#define ID_VIEW_USER_TOOLBAR7           2799
#define ID_VIEW_USER_TOOLBAR8           2800
#define ID_VIEW_USER_TOOLBAR9           2801
#define ID_VIEW_USER_TOOLBAR10          2802
#define ID_VIEW_WORKSPACE               2803
#define ID_VIEW_OUTPUT                  2804
#define ID_MDI_NEW_VERT_GROUP           2838
#define ID_MDI_NEW_HORZ_TAB_GROUP       2839
#define ID_MDI_MOVE_TO_PREV_GROUP       2840
#define ID_MDI_CANCEL                   2841
#define ID_MDI_MOVE_TO_NEXT_GROUP       2842
#define ID_OUTPUT_COPY                  3000
#define ID_OUTPUT_CUT                   3001
#define ID_OUTPUT_CLEAR                 3002
#define ID_OUTPUT_AUTOSCROLL            3003
#define ID_OUTPUT_SAVEAS                3004
#define XT_IDC_DRAGCOPY                 4133
#define XT_IDC_DRAGMOVE                 4134
#define XT_IDC_DRAGNONE                 4135
#define XT_IDC_HANDNONE                 4136
#define XT_IDC_HAND                     4137
#define XTP_IDC_HSPLITBAR               4139
#define XTP_IDC_VSPLITBAR               4141
#define ID_EDIT_NEW                     32850
#define ID_EDIT_DELETE                  32851
#define ID_TREE_EXPAND                  32852
#define ID_TREE_COLLAPSE                32853
#define ID_PACKET_DECODE                32857
#define ID_PACKET_DETAIL                32858

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        325
#define _APS_NEXT_COMMAND_VALUE         32864
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           316
#endif
#endif
